name: macOS 10.14 build check

on:
  push:

jobs:
  build-macos-10-14:
    name: macOS 10.14
    runs-on: andromeda
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install dependencies
        run: |
          brew install gcc boost

      - name: Clone conceal-core
        run: |
          rm -rf cryptonote
          git clone https://github.com/AxVultis/conceal-core.git -b clang cryptonote

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          ccx_ver=${GITHUB_SHA::7}
          release_name="ccx-desktop-macOS-dev-$ccx_ver"
          app_name="CONCEAL-GUI.app"

          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -DCMAKE_C_FLAGS="-mmacosx-version-min=10.12" -DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.12" -D CMAKE_BUILD_TYPE=Release ../..
          make -j4
          macdeployqt "$app_name"
          cpack
          mkdir "$release_name"
          mv *.dmg "$release_name".dmg
          mv "$release_name".dmg "$release_name"

          echo "::set-output name=release_name::${release_name}"
          echo "::set-output name=artifact_path::$build_folder/$release_name"

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
